const express = require("express");
const healthRoutes = require("./health.routes");
const authRoutes = require("./auth.routes");
const profileRoutes = require("./profile.routes");
const groupRoutes = require("./group.routes");
const trailRoutes = require("./trail.routes");
const checklistRoutes = require("./checklist.routes");
const messageRoutes = require("./message.routes");
const adminRoutes = require("./admin.routes");
const analyticsRoutes = require("./analytics.routes");
const subscriptionRoutes = require("./subscription.routes");
const paymentRoutes = require("./payment.routes");
const premiumRoutes = require("./premium.routes");
const mapRoutes = require("./map.routes");
const activityRoutes = require("./activity.routes");
const homestayRoutes = require("./homestay.routes");
const reviewRoutes = require("./review.routes");
const eventRoutes = require("./event.routes");
const localServiceRoutes = require("./localservice.routes");

const router = express.Router();

router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/profile", profileRoutes);
router.use("/groups", groupRoutes);
router.use("/groups", messageRoutes);
router.use("/trails", trailRoutes);
router.use("/checklists", checklistRoutes);
router.use("/admin", adminRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/subscriptions", subscriptionRoutes);
router.use("/payments", paymentRoutes);
router.use("/premium", premiumRoutes);
router.use("/map", mapRoutes);
router.use("/activities", activityRoutes);
router.use("/homestays", homestayRoutes);
router.use("/reviews", reviewRoutes);
router.use("/events", eventRoutes);
router.use("/localservices", localServiceRoutes);

module.exports = router;
